#!/usr/bin/env bash

target="$1"
width="${FZF_PREVIEW_COLUMNS:-80}"
height="${FZF_PREVIEW_LINES:-60}"
mimetype=$(file --mime-type -b "$target")

case "$mimetype" in
    inode/directory)
        tree -C -L 1 "$target"
        ;;
    text/*)
        bat --color=always --theme=ansi -pp "$target"
        ;;
    image/*)
        fzf-preview-image $target
        ;;
    application/json)
        jq -C . "$target" || bat --color=always --theme=ansi -pp "$target"
        ;;
    *)
        echo Preview for file type \"$mimetype\" unavailable
esac
