#!/usr/bin/env bash

options=("Shutdown" "Suspend" "Logout" "Restart")
[[ -f /boot/EFI/Microsoft/Boot/bootmgfw.efi ]] && options+=("Windows")

menu=$(printf "%s\n" "${options[@]}")

lines=${#options[@]}

# Show the rofi menu
choice=$(echo -e "$menu" | rofi -dmenu -theme-str "window { width: 150px; } listview { lines: ${lines}; } element-text { horizontal-align: 0.50; } configuration { show-icons: false; } inputbar { enabled: false; }")

case "$choice" in
    Shutdown)
        systemctl poweroff
        ;;
    Restart)
        systemctl reboot
        ;;
    Suspend)
        systemctl suspend
        ;;
    Logout)
        uwsm stop
        ;;
    "Windows")
        # If --boot-loader-menu is set to 0, it has an infinite timeout, which i dont want
        systemctl reboot --boot-loader-entry=auto-windows --boot-loader-menu=1
        ;;
    *)
        # Do nothing on invalid or no selection
        ;;
esac
